### ISSUE TITLE
date format for <START_TIME> and <END_TIME> when creating a subnet doesn't work on macbook Pro

### ISSUE THREAD

**Issue by pedro-sys** [AshAvalanche/ash-docs#54]
subnet_validator_start_time: '{{ lookup("pipe", "date -d ''2 minutes'' --rfc-3339=seconds").replace(" ", "T")  }}' # in 2 minutes
subnet_validator_end_time: '{{ lookup("pipe", "date -d ''1 week'' --rfc-3339=seconds").replace(" ", "T")  }}' # in 1 week

**Comment by leopaul36** [comment]
Fixed with https://github.com/AshAvalanche/ansible-avalanche-collection/pull/75
